# Autogenerated wrapper script for msgpack_jll for aarch64-apple-darwin
export libmsgpack_c

JLLWrappers.@generate_wrapper_header("msgpack")
JLLWrappers.@declare_library_product(libmsgpack_c, "@rpath/libmsgpack-c.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmsgpack_c,
        "lib/libmsgpack-c.2.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
