# Autogenerated wrapper script for msgpack_jll for i686-linux-gnu
export libmsgpack_c

JLLWrappers.@generate_wrapper_header("msgpack")
JLLWrappers.@declare_library_product(libmsgpack_c, "libmsgpack-c.so.2")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmsgpack_c,
        "lib/libmsgpack-c.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
